runtime: go111

env: standard
service: default
instance_class: F1
handlers:
  - url: /cron/worker/.*
    script: auto
    login: admin

  - url: '/.*'
    script: auto

env_variables:
  PROJECT_IDS: <YOUR_PROJECT_ID_1>,<YOUR_PROJECT_ID_2>
  OPERATION_FILTER: operationType="compute.instances.migrateOnHostMaintenance" OR operationType="compute.instances.hostError"
  TO: <YOUR_EMAIL_1>,<YOUR_EMAIL_2>
  TIMEZONE: Asia/Taipei
  # DATABASE you can chose `datastore` or `memcache`
  DATABASE: memcache
